pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "this is working..."'
                sh 'whoami'
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
