pipeline {
    agent any
    stages {
        
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build') {
            steps {
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Build docker'){
            steps{
                def docker_file = './docker/Dockerfile'
                sh (
                    './jenkins/scripts/build_docker.sh ' + docker_file, 
                    returnStdout:true
                )
            }
        }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //     }
        // }
    }
}
